services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uchibot
    ports:
      - "8000:8000"
    volumes:
      - /root/Downloads:/app/Downloads
