-- Table: public.alter_bot_book

-- DROP TABLE IF EXISTS public.alter_bot_book;

CREATE TABLE IF NOT EXISTS public.alter_bot_book
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying COLLATE pg_catalog."default" NOT NULL,
    author character varying COLLATE pg_catalog."default" NOT NULL,
    url character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alter_bot_book_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.alter_bot_book
    OWNER to postgres;
-- Index: idx_books_title_author

-- DROP INDEX IF EXISTS public.idx_books_title_author;

CREATE INDEX IF NOT EXISTS idx_books_title_author
    ON public.alter_bot_book USING gin
    (((title::text || ' '::text) || author::text) COLLATE pg_catalog."default" gin_trgm_ops)
    TABLESPACE pg_default;
-- Index: idx_books_title_author_trgm

-- DROP INDEX IF EXISTS public.idx_books_title_author_trgm;

CREATE INDEX IF NOT EXISTS idx_books_title_author_trgm
    ON public.alter_bot_book USING gin
    (((title::text || ' '::text) || author::text) COLLATE pg_catalog."default" gin_trgm_ops)
    TABLESPACE pg_default;
-- Index: idx_books_trgm

-- DROP INDEX IF EXISTS public.idx_books_trgm;

CREATE INDEX IF NOT EXISTS idx_books_trgm
    ON public.alter_bot_book USING gin
    (((title::text || ' '::text) || author::text) COLLATE pg_catalog."default" gin_trgm_ops)
    TABLESPACE pg_default;